# Generated by Django 2.2.7 on 2019-11-15 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_auto_20191116_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('emp', 'Employer'), ('app', 'Applicant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='companyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 2, 32, 21, 539782), null=True, verbose_name='established year'),
        ),
    ]
