# Generated by Django 2.2.7 on 2019-11-16 08:58

import Accounting.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_auto_20191116_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[Accounting.validators.PhoneValidator()]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 12, 28, 18, 829727), null=True, verbose_name='established year'),
        ),
    ]
