# Generated by Django 2.2.7 on 2019-11-16 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0006_auto_20191116_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fieldsOfExpertise',
            field=models.CharField(choices=[('prog', 'Programmer'), ('mech', 'Mechanical Engineer')], default='prog', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 14, 34, 45, 915692), null=True, verbose_name='established year'),
        ),
    ]
