# Generated by Django 2.2.7 on 2019-11-16 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_auto_20191116_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 14, 35, 47, 178199), null=True, verbose_name='established year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fieldsOfExpertise',
            field=models.CharField(blank=True, choices=[('prog', 'Programmer'), ('mech', 'Mechanical Engineer')], max_length=20),
        ),
    ]
