# Generated by Django 2.2.7 on 2019-11-16 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_auto_20191116_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 14, 42, 47, 479732), null=True, verbose_name='established year'),
        ),
    ]
