# Generated by Django 2.2.7 on 2019-11-16 11:15

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_auto_20191116_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 14, 45, 30, 325447), null=True, verbose_name='established year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fieldsOfExpertise',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prog', 'Programmer'), ('mech', 'Mechanical Engineer')], max_length=20),
        ),
    ]
