# Generated by Django 2.2.7 on 2019-11-16 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0011_auto_20191116_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 15, 43, 19, 994827), null=True, verbose_name='established year'),
        ),
    ]
