# Generated by Django 2.2.7 on 2019-11-16 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0012_auto_20191116_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, default='fork-exec-exit-wait.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 16, 9, 51, 564211), null=True, verbose_name='established year'),
        ),
    ]
