# Generated by Django 2.2.7 on 2019-11-16 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0014_auto_20191116_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 17, 25, 0, 295563), null=True, verbose_name='established year'),
        ),
    ]
