# Generated by Django 2.2.7 on 2019-11-16 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0015_auto_20191116_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 18, 4, 54, 629876), null=True, verbose_name='established year'),
        ),
    ]
