# Generated by Django 2.2.7 on 2019-11-16 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0017_auto_20191116_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 18, 13, 28, 288986), null=True, verbose_name='established year'),
        ),
    ]
