# Generated by Django 2.2.7 on 2019-11-14 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 19, 7, 18, 237013), verbose_name='established year'),
        ),
    ]
