# Generated by Django 2.2.7 on 2019-11-15 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_auto_20191115_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 55, 31, 350591), verbose_name='established year'),
        ),
    ]
