# Generated by Django 2.2.7 on 2019-11-14 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_auto_20191114_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 22, 35, 38, 746099), verbose_name='established year'),
        ),
    ]
