# Generated by Django 2.2.7 on 2019-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20191113_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='password',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='userName',
            field=models.CharField(max_length=50, unique=True, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='userName',
            field=models.CharField(max_length=50, unique=True, verbose_name='user name'),
        ),
    ]
