# Generated by Django 2.2.7 on 2019-11-15 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_auto_20191115_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 58, 10, 912084), verbose_name='established year'),
        ),
    ]
