# Generated by Django 2.2.7 on 2019-11-13 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_auto_20191113_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[09][0-9]*$', 'Only digits are allowed.')]),
        ),
    ]
