# Generated by Django 2.2.7 on 2019-11-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Accounting', '0006_auto_20191115_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
