# Generated by Django 2.2.7 on 2019-11-15 12:29

import Accounting.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_delete_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('companyName', models.CharField(max_length=50, verbose_name='company name')),
                ('establishedYear', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 59, 26, 110886), verbose_name='established year')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[Accounting.validators.PhoneValidator()])),
            ],
            options={
                'abstract': False,
            },
            bases=('Accounting.user',),
        ),
    ]
