# Generated by Django 2.2.7 on 2019-11-15 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 16, 1, 57, 935973), verbose_name='established year'),
        ),
    ]
