# Generated by Django 2.2.7 on 2019-11-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_auto_20191115_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 16, 2, 58, 973317), verbose_name='established year'),
        ),
    ]
