# Generated by Django 2.2.7 on 2019-11-15 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0010_auto_20191115_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 16, 55, 0, 682025), verbose_name='established year'),
        ),
    ]
