# Generated by Django 2.2.7 on 2019-11-15 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0011_auto_20191115_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 17, 5, 55, 762202), verbose_name='established year'),
        ),
    ]
