# Generated by Django 2.2.7 on 2019-11-15 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0012_auto_20191115_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='establishedYear',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 17, 30, 31, 866199), verbose_name='established year'),
        ),
    ]
