# Generated by Django 2.2.7 on 2019-11-14 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, upload_to='')),
                ('exp_data', models.DateField(blank=True, default=datetime.date.today)),
                ('fieldsOfExpertise', models.CharField(choices=[('programming', 'Programmer'), ('mechanical_engineering', 'Mechanical Engineer')], max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='Accounting.Employer')),
            ],
        ),
    ]
