# Generated by Django 2.2.7 on 2019-11-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
