# Generated by Django 2.2.7 on 2019-11-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commercial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='exp_data',
            new_name='expDate',
        ),
    ]
