# Generated by Django 2.2.7 on 2019-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20191114_2235'),
        ('Commercial', '0002_auto_20191114_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='ads', to='Accounting.Applicant'),
        ),
    ]
