# Generated by Django 2.2.7 on 2019-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='fieldsOfExpertise',
            field=models.CharField(choices=[('prog', 'Programmer'), ('mech', 'Mechanical Engineer')], max_length=20),
        ),
    ]
