# Generated by Django 2.2.7 on 2019-11-16 14:34

import Accounting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commercial', '0003_auto_20191116_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='salary',
            field=models.CharField(max_length=10, validators=[Accounting.validators.IsNumberValidator]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
